import type { AmberListing } from "./types";

/**
 * Sample inventory shaped like a normalized Amber listing. Used whenever
 * AMBER_PARTNER_UUID isn't configured yet, or if the live Amber API is
 * unreachable/errors, so Find Rooms always has something to show.
 */
export const MOCK_LISTINGS: AmberListing[] = [
  {
    id: "mock-10231",
    propertyName: "Stratford One",
    city: "London",
    country: "United Kingdom",
    university: "University College London",
    universityDistance: "3.2 km",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Studio",
    price: 365,
    currency: "GBP",
    priceDuration: "weekly",
    billsPolicy: "All bills included",
    amenities: ["Gym", "24/7 Security", "High-speed Wi-Fi", "Study Room"],
    rating: 4.7,
    reviewsCount: 214,
    availableFrom: "2026-09-01",
    genderPreference: "Any",
    verified: true,
    instantBook: true,
  },
  {
    id: "mock-10456",
    propertyName: "Vita Student Manchester",
    city: "Manchester",
    country: "United Kingdom",
    university: "University of Manchester",
    universityDistance: "1.1 km",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Ensuite",
    price: 245,
    currency: "GBP",
    priceDuration: "weekly",
    billsPolicy: "All bills included",
    amenities: ["Cinema Room", "Gym", "Laundry", "On-site Staff"],
    rating: 4.5,
    reviewsCount: 178,
    availableFrom: "2026-09-08",
    genderPreference: "Any",
    verified: true,
    instantBook: false,
  },
  {
    id: "mock-10789",
    propertyName: "Urbanest King's Cross",
    city: "London",
    country: "United Kingdom",
    university: "King's College London",
    universityDistance: "4.6 km",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Private Room",
    price: 298,
    currency: "GBP",
    priceDuration: "weekly",
    billsPolicy: "All bills included",
    amenities: ["Rooftop Terrace", "Study Room", "Bike Storage"],
    rating: 4.3,
    reviewsCount: 132,
    availableFrom: "2026-08-25",
    genderPreference: "Female Only",
    verified: true,
    instantBook: true,
  },
  {
    id: "mock-11002",
    propertyName: "Iglu Birmingham Central",
    city: "Birmingham",
    country: "United Kingdom",
    university: "University of Birmingham",
    universityDistance: "2.4 km",
    images: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522771930-78848d9293e8?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Shared Room",
    price: 165,
    currency: "GBP",
    priceDuration: "weekly",
    billsPolicy: "Partial bills included",
    amenities: ["Games Room", "Laundry", "Common Kitchen"],
    rating: 4.1,
    reviewsCount: 96,
    availableFrom: "2026-09-15",
    genderPreference: "Any",
    verified: true,
    instantBook: false,
  },
  {
    id: "mock-11215",
    propertyName: "Scape Melbourne Central",
    city: "Melbourne",
    country: "Australia",
    university: "University of Melbourne",
    universityDistance: "0.8 km",
    images: [
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Studio",
    price: 420,
    currency: "AUD",
    priceDuration: "weekly",
    billsPolicy: "All bills included",
    amenities: ["Pool", "Gym", "Co-working Lounge", "24/7 Security"],
    rating: 4.8,
    reviewsCount: 301,
    availableFrom: "2026-07-14",
    genderPreference: "Any",
    verified: true,
    instantBook: true,
  },
  {
    id: "mock-11340",
    propertyName: "The Standard Toronto",
    city: "Toronto",
    country: "Canada",
    university: "University of Toronto",
    universityDistance: "1.9 km",
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Ensuite",
    price: 310,
    currency: "CAD",
    priceDuration: "weekly",
    billsPolicy: "All bills included",
    amenities: ["Rooftop Terrace", "Gym", "Study Pods"],
    rating: 4.4,
    reviewsCount: 121,
    availableFrom: "2026-08-30",
    genderPreference: "Male Only",
    verified: true,
    instantBook: false,
  },
  {
    id: "mock-11482",
    propertyName: "Base Berlin Mitte",
    city: "Berlin",
    country: "Germany",
    university: "Humboldt University of Berlin",
    universityDistance: "2.7 km",
    images: [
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Twin Room",
    price: 190,
    currency: "EUR",
    priceDuration: "weekly",
    billsPolicy: "Bills excluded",
    amenities: ["Bike Storage", "Common Kitchen", "Laundry"],
    rating: 4.0,
    reviewsCount: 74,
    availableFrom: "2026-09-20",
    genderPreference: "Any",
    verified: false,
    instantBook: false,
  },
  {
    id: "mock-11599",
    propertyName: "Yugo Leeds Sky Plaza",
    city: "Leeds",
    country: "United Kingdom",
    university: "University of Leeds",
    universityDistance: "1.4 km",
    images: [
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1615529182904-14819c35db37?q=80&w=1200&auto=format&fit=crop",
    ],
    roomType: "Private Room",
    price: 210,
    currency: "GBP",
    priceDuration: "weekly",
    billsPolicy: "All bills included",
    amenities: ["Sky Lounge", "Gym", "Cinema Room", "Study Room"],
    rating: 4.6,
    reviewsCount: 158,
    availableFrom: "2026-09-05",
    genderPreference: "Any",
    verified: true,
    instantBook: true,
  },
];

export function getMockCities(): string[] {
  return Array.from(new Set(MOCK_LISTINGS.map((l) => l.city))).sort();
}

export function getMockRoomTypes(): string[] {
  return Array.from(new Set(MOCK_LISTINGS.map((l) => l.roomType)));
}
